[package]
name = "bounded-vec"
version = "0.7.1"
license = "CC0-1.0"
authors = ["Denys Zadorozhnyi <denys@zadorozhnyi.com>"]
edition = "2018"
description = "Non-empty rust Vec wrapper with type guarantees on lower and upper bounds for items quantity."
repository = "https://github.com/ergoplatform/bounded-vec"

[lib]
crate-type = ["rlib"]

[dependencies]
thiserror = "1"
serde = {version = "1.0.123", features = ["derive"], optional = true}
proptest = {version = "1.0.0", optional = true}

[features]
arbitrary = ["proptest"]

[dev-dependencies]
proptest = {version = "1.0.0"}
